version: "3.9"

services:

  app:
    build: .

    container_name: fastapi_app

    restart: always

    env_file:
      - .env

    ports:
      - "8000:8000"

    depends_on:
      - db

    volumes:
      - .:/app

  streamlit:
    build: .
    container_name: text_to_sql_streamlit
    volumes:
      - ./:/app
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8501:8501"
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - app

  db:
    image: postgres:15

    container_name: postgres_db

    restart: always

    env_file:
      - .db.env

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  postgres_data: